name: analyses

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  VITE_LOGTO_APP_ID: ${{ secrets.VITE_LOGTO_APP_ID }}
  VITE_LOGTO_APP_ID_M2M: ${{ secrets.VITE_LOGTO_APP_ID_M2M }}
  VITE_LOGTO_APP_ID_M2M_SECRET: ${{ secrets.VITE_LOGTO_APP_ID_M2M_SECRET }}
  VITE_RESOURCE_BUESS: ${{ secrets.VITE_RESOURCE_BUESS }}
  VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
  VITE_LOGTO_SERVE: ${{ secrets.VITE_LOGTO_SERVE }}
  MONGODB_URL: ${{ secrets.MONGODB_URL }}

jobs:
  install:
    runs-on: ubuntu-latest
    environment: 'development'
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.sha }}
      - name: Generate type env
        run: npm run type:env

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cached node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.sha }}
      - name: Eslint
        run: npm run lint:check

  prettier:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cached node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.sha }}
      - name: Prettier
        run: npm run prettier:check

  typescript:
    needs: install
    runs-on: ubuntu-latest
    environment: 'development'
    steps:
      - uses: actions/checkout@v2
      - name: Cached node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.sha }}
      - name: Typescript
        run: npm run type:env && npm run ts:check

  unit_tests:
    needs: install
    runs-on: ubuntu-latest
    environment: 'development'
    steps:
      - uses: actions/checkout@v2
      - name: Cached node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.sha }}
      - name: Unit tests
        run: npm run type:env && npm run seed && npm run test:unit