name: e2e tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: 'development'
    env:
      VITE_MONGODB_URL: ${{ secrets.VITE_MONGODB_URL }}
      VITE_LOGTO_APP_ID: ${{ secrets.VITE_LOGTO_APP_ID }}
      VITE_LOGTO_APP_ID_M2M: ${{ secrets.VITE_LOGTO_APP_ID_M2M }}
      VITE_LOGTO_APP_ID_M2M_SECRET: ${{ secrets.VITE_LOGTO_APP_ID_M2M_SECRET }}
      VITE_RESOURCE_BUESS: ${{ secrets.VITE_RESOURCE_BUESS }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Generate type env
        run: npm run type:env
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
